riscv/rtl/cache/l1_cache.sv
riscv/rtl/memory/memory_controller.sv
riscv/rtl/memory/sram_model.sv
riscv/rtl/soc/riscv_cluster.sv
riscv/rtl/core/alu.sv
riscv/rtl/core/base_decoder.sv
riscv/rtl/core/decoder.sv
riscv/rtl/core/ext_a_decoder.sv
riscv/rtl/core/hazard_unit.sv
riscv/rtl/core/regfile.sv
riscv/rtl/core/forwarding_unit.sv
riscv/rtl/core/branch_predictor.sv
riscv/rtl/core/csr_regfile.sv
riscv/rtl/core/datapath.sv
riscv/include/ahb_if.sv
riscv/include/cache_if.sv
riscv/include/riscv_pkg.sv
riscv/include/coherence_if.sv
riscv/verification/tb/tb_alu.sv
riscv/verification/tb/tb_regfile.sv
riscv/verification/tb/tb_decoder.sv
riscv/verification/tb/tb_hazard_unit.sv
riscv/verification/tb/tb_forwarding_unit.sv
riscv/verification/tb/tb_branch_predictor.sv
riscv/verification/tb/tb_csr_regfile.sv
riscv/verification/tb/tb_l1_cache.sv
riscv/verification/tb/tb_soc.sv
